"""initial

Revision ID: 7c4a09df14a1
Revises:
Create Date: 2026-05-20 00:41:17.430548

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7c4a09df14a1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("price", sa.String(length=32), nullable=True),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_data_key", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index("idx_price", "books", ["price"], unique=False)
    op.create_index("idx_raw_data-gin", "books", ["raw_data"], unique=False, postgresql_using="gin")
    op.create_index("idx_title", "books", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_title", table_name="books")
    op.drop_index("idx_raw_data-gin", table_name="books", postgresql_using="gin")
    op.drop_index("idx_price", table_name="books")
    op.drop_table("books")
    # ### end Alembic commands ###
