"""add raw-data JSONB field

Revision ID: 8036ebd03adb
Revises: 5e95ebe7c3d4
Create Date: 2026-05-07 08:51:50.601461

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8036ebd03adb"
down_revision: Union[str, Sequence[str], None] = "5e95ebe7c3d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books", sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.create_index("idx_raw_data-gin", "books", ["raw_data"], unique=False, postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_raw_data-gin", table_name="books", postgresql_using="gin")
    op.drop_column("books", "raw_data")
    # ### end Alembic commands ###
